version: 2.1

orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@2.6.0

jobs:
  deploy-and-ping:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:UFQjouHOQ5IAByFVtzb4sM8XFK8wSB83BH5aUyxMmLE"
      - run:
          name: SSH into server and ping
          command: |
            ssh -oStrictHostKeyChecking=no root@103.186.65.162 'ping -c 5 google.com'

workflows:
  test-my-deploy:
    jobs:
      - deploy-and-ping:
          filters:
            branches:
              only:
                - circleci-project-setup
